version: '3.4'

services:

  sqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
        
  
  nosqldb: 
    image: mongo
  
  cachdata:
    image: redis:alpine
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  api1:
    image: api1
    build:
      context: .
      dockerfile: project1/API1/Dockerfile
    ports:
      - "5101:80"
      - "7101:443"
    depends_on:
      - sqldb
